#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gato_Tic_Tac_Toe.Resource", IsApplication=true)]

namespace Gato_Tic_Tac_Toe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gato = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gato2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int nulo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int o = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int x = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int btn_iniciaH = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int btn_iniciaM = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int btn_reset = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int btn_salir = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int imageView2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int imageView3 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int imageView4 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int imageView5 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int imageView6 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int imageView7 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int imageView8 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageView9 = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout3 = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int ll_footer = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int ll_header = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ll_tablero = 2131099650;
			
			// aapt resource value: 0x7f060011
			public const int textView1 = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int tv_devolped = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int tv_id = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int MainLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int PierdeGato = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int QuienInicia = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int CODEJS = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
