#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gato_Tic_Tac_Toe.Resource", IsApplication=true)]

namespace Gato_Tic_Tac_Toe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gato = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int nulo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int o = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int o_neg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int x = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int x_neg = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int btn_iniciaH = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int btn_iniciaM = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int btn_reset = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int btn_salir = 2131165205;
			
			// aapt resource value: 0x7f070001
			public const int btncerrardialog = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int imageView1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int imageView2 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int imageView3 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int imageView4 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int imageView5 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int imageView6 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int imageView7 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int imageView8 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int imageView9 = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout2 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout3 = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int ll_footer = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int ll_header = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int ll_tablero = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int textView1 = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int tv_devolped = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int tv_id = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int tvalertwiner = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AlertLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MainLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int PierdeGato = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int QuienInicia = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int pruebamac = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int CODEJS = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
